### ISSUE TITLE
no jungle biomes

### ISSUE THREAD

**Issue by vitaminx** [minetest-mods/moretrees#11]
Hi, after days of searching I've finally decided to open an issue for your mod. It seems to be impossible to find jungletrees.
I've got several complains from players on the server and I generated a single-player map with mapgen v6 with only the moretrees and plants_lib mods enabled and still I can't find jungle trees anywhere, except once I have found a horizontal jungle tree lying on the ground.
All other trees and plants seem to be OK.

I do get a warning at server startup, maybe related:

    18:02:36: VERBOSE[main]: ItemDefManager: setting alias technic:rubber_tree_sapling -> moretrees:rubber_tree_sapling
    18:02:36: VERBOSE[main]: ItemDefManager: setting alias farming_plus:rubber_sapling -> moretrees:rubber_tree_sapling
    18:02:36: VERBOSE[main]: ItemDefManager: setting alias farming:rubber_sapling -> moretrees:rubber_tree_sapling
    18:02:36: INFO[main]: WARNING: Not registering alias, item with same name is already defined: default:junglesapling -> moretrees:jungletree_sapling
    18:02:36: VERBOSE[main]: ItemDefManager: setting alias moretrees:jungletree_trunk_sideways -> moreblocks:horizontal_jungle_tree
    18:02:36: VERBOSE[main]: ItemDefManager: setting alias moretrees:jungletree_trunk -> default:jungletree
    18:02:36: VERBOSE[main]: ItemDefManager: setting alias moretrees:jungletree_planks -> default:junglewood

I'm using minetest 0.4.11+repack-1 on Debian Linux.

ty, vitaminx

**Comment by VanessaE** [comment]
Those errors probably aren't relevant, as I was in fact just using the moretrees jungle tree saplings yesterday in a world.  However I have noticed that they don't seem to spawn at mapgen time anymore.

**Comment by sofar** [comment]
I'll close this issue soon unless someone confirms that this is still a problem
