### ISSUE TITLE
Acacia Trees no Longer spawning in Savanna

### ISSUE THREAD

**Issue by Routhinator** [minetest-mods/moretrees#15]
Not sure what happened here. My commit was tested and working against 5048d4e894e40608a318fad88ee1cf8a79150b46 but when you merged it with your changes they now will not spawn at all if spawned on mapgen. I cannot seem to identify why. I've seen plants_lib spawn one on grass but that is all.

**Comment by VanessaE** [comment]
Can you check this with the latest minetest_game?  Moretrees now uses the default acacia nodes.

**Comment by sofar** [comment]
@Routhinator no reply in 6 months, will close unless there's a reply soon.
