### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by yukaputz** [minetest-mods/moretrees#21]
Hi, sorry to bother, I have been trying to setup a dedicated minetest server for my 5 kids on a ubuntu headless server.  I'm just about there but I am running into issues with biome_lib.  Would you be able to take a look below and let me know  what else I need to do?  Here is a listing of my mod directory

**LISTING**
yukaputz@media-1:~/.minetest/mods$ ls
animals_modpack-2.5.0  cme                                                    hud_hunger        pilzadam                  VanessaE-homedecor_modpack-9b61d20
bedrock                craftingpack                                           moreores-master   plantlife_modpack-master
biome_lib-master       farming_plus-086599805b642662ba680e1f18c271a4a972c9e3  moretrees-master  torches

**And here is what I get when I start minetestserver**

yukaputz@media-1:~/.minetest/mods$ minetestserver --config /home/yukaputz/.minetest/minetestserver.conf
Automatically selecting world at [/home/yukaputz/.minetest/worlds/world]
13:51:49: ERROR[main]: mod "along_shore" has unsatisfied dependencies:  "biome_lib" "flowers_plus"
13:51:49: ERROR[main]: mod "bushes" has unsatisfied dependencies:  "biome_lib"
13:51:49: ERROR[main]: mod "bushes_classic" has unsatisfied dependencies:  "biome_lib"
13:51:49: ERROR[main]: mod "dryplants" has unsatisfied dependencies:  "biome_lib"
13:51:49: ERROR[main]: mod "ferns" has unsatisfied dependencies:  "biome_lib"
13:51:49: ERROR[main]: mod "flowers_plus" has unsatisfied dependencies:  "biome_lib"
13:51:49: ERROR[main]: mod "molehills" has unsatisfied dependencies:  "biome_lib"
13:51:49: ERROR[main]: mod "poisonivy" has unsatisfied dependencies:  "biome_lib"
13:51:49: ERROR[main]: mod "trunks" has unsatisfied dependencies:  "biome_lib" "bushes" "ferns"
13:51:49: ERROR[main]: mod "vines" has unsatisfied dependencies:  "biome_lib"
13:51:49: ERROR[main]: mod "woodsoils" has unsatisfied dependencies:  "biome_lib" "bushes" "ferns" "trunks"
13:51:49: ERROR[main]: mod "youngtrees" has unsatisfied dependencies:  "biome_lib"
13:51:49: ERROR[main]: mod "moretrees-master" has unsatisfied dependencies:  "biome_lib"
13:51:49: ERROR[main]: The following mods could not be found: "biome_lib-master"
13:51:49: ERROR[main]: ========== ERROR FROM LUA ===========
13:51:49: ERROR[main]: Failed to load and run script from
13:51:49: ERROR[main]: /home/yukaputz/.minetest/mods/animals_modpack-2.5.0/factions/init.lua:
13:51:49: ERROR[main]: ...z/.minetest/mods/animals_modpack-2.5.0/factions/init.lua:17: attempt to index global 'core' (a nil value)
13:51:49: ERROR[main]: stack traceback:
13:51:49: ERROR[main]:  ...z/.minetest/mods/animals_modpack-2.5.0/factions/init.lua:17: in main chunk
13:51:49: ERROR[main]: ======= END OF ERROR FROM LUA ========
13:51:49: ERROR[main]: Server: Failed to load and run /home/yukaputz/.minetest/mods/animals_modpack-2.5.0/factions/init.lua
13:51:49: ERROR[main]: ERROR: An unhandled exception occurred: ModError: Failed to load and run /home/yukaputz/.minetest/mods/animals_modpack-2.5.0/factions/init.lua

**Comment by Xanthin** [comment]
> 13:51:49: ERROR[main]: The following mods could not be found: "biome_lib-master"

Have you tried to rename the folder from "biome_lib-master" into "biome_lib"? Usual this suffix "-master" is added by github automatical (changes if you download from a different branch) and needs to be deleted to match the mod folder name with what it is named in code and depends file.
Also check the other mods you have. (maybe helps too: [minetest wiki: Installing Mods](http://wiki.minetest.net/Installing_Mods))

Although there is the general possibility for mods to add a **mod.conf** file with the correct mod name there to solve this issue in general, if I understood correct. (see [mt forum post](https://forum.minetest.net/viewtopic.php?p=201061#p201061)) Something useful to add to your mods, @VanessaE ? :)

**Comment by sofar** [comment]
62eb522948a8b847567a832d7232dc61b5c10ae4
