### ISSUE TITLE
Tree spawn in water

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/moretrees#32]
Sometimes tree spawns in water like this, missing two blocks of trunk:
https://i.imgur.com/XELNTQB.jpg or https://i.imgur.com/je2cjn4.jpg or https://i.imgur.com/pJ144Ej.png

@VanessaE

**Comment by VanessaE** [comment]
That's the core mapgen doing that ("cavegen griefing").  Not sure how to fix it.

**Comment by paramat** [comment]
'is_ground_content = false' in the nodedef of tree trunks and leaves.

**Comment by sofar** [comment]
seems it's set to `true` for some of the nodes:

https://github.com/minetest-mods/moretrees/search?utf8=%E2%9C%93&q=is_ground_content

**Comment by Fixer-007** [comment]
Any ideas here?

**Comment by VanessaE** [comment]
3d7bcca134b1904123c5ec54cf65087a7c85d53f

**Comment by Fixer-007** [comment]
Thanks!
