### ISSUE TITLE
Incompatibility to leavedecay of minetest_game master

### ISSUE THREAD

**Issue by tchncs** [minetest-mods/moretrees#33]
minetest_game no longer uses the old decay abm and the registration has changed.
It should be something like:

```
        default.register_leafdecay({
            trunks = {"moretrees:"..treename.."_trunk"},
            leaves = {"moretrees:"..treename.."_leaves"},
            radius = decay,
        })
-- ^ this actually didn't work for some reason
```
New lua_api entry:
https://github.com/minetest/minetest_game/commit/60e5b299af564f250af8304b5146f79693c314ff#diff-8eb62e836e64c72a439c178d35c178a8R661

I am sorry, i try to do this since two days and don't find enough time. :(

**Comment by VanessaE** [comment]
2967c107d8e90a531ded53357e83ef904c3ea6cd
