### ISSUE TITLE
Leaves cut through the stem

### ISSUE THREAD

**Issue by HybridDog** [minetest-mods/moretrees#34]
![screenshot_20170316_162259](https://cloud.githubusercontent.com/assets/3192173/24003986/57085cd2-0a65-11e7-9895-7d44f5c0b0b0.png)
![screenshot_20170316_162128](https://cloud.githubusercontent.com/assets/3192173/24003992/5f5a3608-0a65-11e7-954d-6e9852901cea.png)

**Comment by VanessaE** [comment]
Can't be fixed, it's an engine issue.  Discussed it with RBA back when L-system trees were instituted, but we never came to a good resolution.

**Comment by HybridDog** [comment]
Is there always only one leaves or fruit node between the trunk nodes?

**Comment by VanessaE** [comment]
I don't know, offhand, kinda depends on how the engine runs the L-system stuff.  And actually maybe "cantfix" is the wrong label, rather "wontfix", since it's would require changes to the affected trees' models, and such a minor issue that almost no one could see anyway :smile:

**Comment by HybridDog** [comment]
I tried capitating some spruce trees, in my experience it's always one leaves/fruits node. When players build tree houses and replace the mid trunks with ladders, they may notice the cutting leaves…

**Comment by VanessaE** [comment]
Does it only affect spruce (and birch)?

**Comment by HybridDog** [comment]
No, jungletree is also affected and l just noticed that the sequoia stem is quite eroded:
![screenshot_20170318_222145](https://cloud.githubusercontent.com/assets/3192173/24076117/9eed5d0c-0c29-11e7-9df9-7f944c390d36.png)

**Comment by sofar** [comment]
I think an easy fix would be to change the L tree schematics to place leaves first and then trunks?

**Comment by VanessaE** [comment]
That would require an engine change - some sort of buffering per node type, as L-system trees are basically fractals.

**Comment by HybridDog** [comment]
Can't you simply add a symbol for putting a leaves if there's no trunk yet?

**Comment by VanessaE** [comment]
That might work too.  Didn't think of that.  In either case, the model just needs tweaked to avoid the issue.

**Comment by HybridDog** [comment]
What's the maximum possible amount of leaves above each other cutting through the stem?
(l need to know if [for treecapitator](https://github.com/HybridDog/treecapitator/commit/337756eb41a85e0c033ab2b18381cf71557c696d#diff-43fe7c8c6ef8344aaf43e173d7bb983c).)

**Comment by VanessaE** [comment]
I'm afraid I don't know for sure. Probably not more than one, though.  L-system was always a bit confusing to me.

**Comment by HybridDog** [comment]
Is this fixed yet?

**Comment by VanessaE** [comment]
Not going to bother fixing it.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/pull/5918 merged.
