### ISSUE TITLE
acacia leaves don't fully decay

### ISSUE THREAD

**Issue by DS-Minetest** [minetest-mods/moretrees#38]
After digging an acacia tree (with + trunk, x would look a bit different), you can see such a pattern:
![screenshot_20170629_200254](https://user-images.githubusercontent.com/7613443/27744482-f1772da4-5dbf-11e7-9e19-92a8ccf9e8c3.png)
Maybe this is because of the too low decay range of the tree node.
Also I'm not sure, but I think, apple trees don't decay at all.

**Comment by VanessaE** [comment]
Acacias have been removed from this mod entirely (only left some aliases).  Let minetest_game handle them its own way.

**Comment by VanessaE** [comment]
The problem with apple tree leaves not decaying seems to be fixed now as well (be sure you update plantlife_modpack also).  Not sure what actually FIXED it, but it works now :grin:
